openapi: 3.0.3
info:
  title: Addresses and Coordinates
  description: API to manage addresses and obtain the distance that can be relative
    to the nearest registered address or the distance between two addresses registered
    or not
  version: 0.2.8
servers:
- url: /
paths:
  /api/addresses:
    get:
      summary: Returns a list of addresses
      operationId: api_addresses_get
      responses:
        "200":
          description: A JSON array of addresses information and coordinates
          content:
            application/json:
              schema:
                type: array
                example:
                - _id:
                    $oid: 655de875051df4458d1d32be
                  number: "520"
                  street: AV. Pasteur
                  district: Urca
                  city: Rio de Janeiro
                  state: RJ
                  country: Brasil
                  location:
                    type: Point
                    coordinates:
                    - -22.9489641
                    - -43.1546316
                - _id:
                    $oid: 6563ab4b514febb49306a795
                  street: Parque Nacional da Tijuca
                  district: Alto da Boa Vista
                  city: Rio de Janeiro
                  state: RJ
                  country: Brasil
                  location:
                    type: Point
                    coordinates:
                    - -22.9516393
                    - -43.2104765
                items:
                  type: object
                x-content-type: application/json
      x-openapi-router-controller: swagger_server.controllers.default_controller
    post:
      summary: Register an address
      operationId: api_addresses_post
      responses:
        "200":
          description: A string informing about success
          content:
            application/json:
              schema:
                type: string
                example: Registration created successfully
                x-content-type: application/json
      x-openapi-router-controller: swagger_server.controllers.default_controller
components: {}

