openapi: 3.0.3
info:
  title: Addresses and Coordinates
  description: API to manage addresses and obtain the distance that can be relative
    to the nearest registered address or the distance between two addresses registered
    or not
  version: 0.2.8
servers:
- url: http://localhost:5000/v1
  description: Sandbox server (uses test data)
paths:
  /addresses:
    get:
      tags:
      - Address
      summary: Returns a list of addresses
      operationId: addresses_get
      responses:
        "200":
          description: A JSON array of addresses information and coordinates
          content:
            application/json:
              schema:
                type: array
                example:
                - _id:
                    $oid: 655de875051df4458d1d32be
                  number: "520"
                  street: AV. Pasteur
                  district: Urca
                  city: Rio de Janeiro
                  state: RJ
                  country: Brazil
                  location:
                    type: Point
                    coordinates:
                    - -22.9489641
                    - -43.1546316
                - _id:
                    $oid: 6563ab4b514febb49306a795
                  street: Parque Nacional da Tijuca
                  district: Alto da Boa Vista
                  city: Rio de Janeiro
                  state: RJ
                  country: Brazil
                  location:
                    type: Point
                    coordinates:
                    - -22.9516393
                    - -43.2104765
                items:
                  type: object
                x-content-type: application/json
      x-openapi-router-controller: swagger_server.controllers.address_controller
    post:
      tags:
      - Address
      summary: Register an address
      operationId: addresses_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Address'
        required: true
      responses:
        "200":
          description: An id of the created document
          content:
            application/json:
              schema:
                type: string
                example: 6563ab4b514febb49306a795
                x-content-type: application/json
      x-openapi-router-controller: swagger_server.controllers.address_controller
  /address/{id}:
    get:
      tags:
      - Address
      summary: Return an object address
      operationId: address_id_get
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          maxItems: 1
          type: string
        example: 6563ab4b514febb49306a795
      responses:
        "200":
          description: An object informing the address and his coordinates
          content:
            application/json:
              schema:
                type: object
                example:
                  _id:
                    $oid: 6563ab4b514febb49306a795
                  street: Parque Nacional da Tijuca
                  district: Alto da Boa Vista
                  city: Rio de Janeiro
                  state: RJ
                  country: Brazil
                  location:
                    type: Point
                    coordinates:
                    - -22.9516393
                    - -43.2104765
                x-content-type: application/json
        "404":
          description: Error message if the object not found
          content:
            application/json:
              schema:
                type: string
                example: "An error has occurred: Address not found"
                x-content-type: application/json
      x-openapi-router-controller: swagger_server.controllers.address_controller
    put:
      tags:
      - Address
      summary: Update an address and return an object address with the new values
      operationId: address_id_put
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          maxItems: 1
          type: string
        example: 6563ab4b514febb49306a795
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Address'
        required: true
      responses:
        "200":
          description: An object informing the new address and his coordinates information
          content:
            application/json:
              schema:
                type: object
                example:
                  _id:
                    $oid: 6563ab4b514febb49306a795
                  street: Parque Nacional da Tijuca
                  district: Alto da Boa Vista
                  city: Rio de Janeiro
                  state: RJ
                  country: Brazil
                  location:
                    type: Point
                    coordinates:
                    - -22.9516393
                    - -43.2104765
                x-content-type: application/json
        "400":
          description: Error message if the object not found
          content:
            application/json:
              schema:
                type: string
                example: "Invalid parameter value: "
                x-content-type: application/json
      x-openapi-router-controller: swagger_server.controllers.address_controller
    delete:
      tags:
      - Address
      summary: Delete an address and return a message informing whether the deletion
        process was successful
      operationId: address_id_delete
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          maxItems: 1
          type: string
        example: 6563ab4b514febb49306a795
      responses:
        "200":
          description: Successful message
          content:
            application/json:
              schema:
                type: string
                example: Registration deleted successfully
                x-content-type: application/json
        "404":
          description: Error message
          content:
            application/json:
              schema:
                type: string
                example: "An error has occurred: Error deleting or non-existing record"
                x-content-type: application/json
      x-openapi-router-controller: swagger_server.controllers.address_controller
  /distance/closest:
    get:
      tags:
      - Distance
      summary: Return an object with the closest location to the given coordinates
        and the distance in meters
      operationId: distance_closest_get
      parameters:
      - name: lat
        in: query
        required: true
        style: form
        explode: true
        schema:
          maxItems: 1
          type: number
        example: -22.910288105803257
      - name: lng
        in: query
        required: true
        style: form
        explode: true
        schema:
          maxItems: 1
          type: number
        example: -43.16440758828707
      responses:
        "200":
          description: An object address with the distance that represent the closest
            register to the given coordinates
          content:
            application/json:
              schema:
                type: object
                example:
                - _id:
                    $oid: 655de875051df4458d1d32be
                  number: "520"
                  street: AV. Pasteur
                  district: Urca
                  city: Rio de Janeiro
                  state: RJ
                  country: Brazil
                  location:
                    type: Point
                    coordinates:
                    - -22.9489641
                    - -43.1546316
                  distance: 26481.382810215204
                x-content-type: application/json
        "400":
          description: Return an error message
          content:
            application/json:
              schema:
                type: string
                example: "Invalid parameter value: Invalid latitude or longitude value"
                x-content-type: application/json
      x-openapi-router-controller: swagger_server.controllers.distance_controller
  /distance/addresses:
    get:
      tags:
      - Distance
      summary: Return the distance between two given addresses
      operationId: distance_addresses_get
      parameters:
      - name: start_address
        in: query
        required: true
        style: form
        explode: true
        schema:
          $ref: '#/components/schemas/Address'
      - name: end_address
        in: query
        required: true
        style: form
        explode: true
        schema:
          $ref: '#/components/schemas/Address'
      responses:
        "200":
          description: A number that represent the distance in meters
          content:
            application/json:
              schema:
                type: number
                example: 5725.929424237887
                x-content-type: application/json
        "400":
          description: Error mesage
          content:
            application/json:
              schema:
                type: string
                example: "Error in geocoding request: Invalid Address, no coordinates\
                  \ were found for the address provided"
                x-content-type: application/json
      x-openapi-router-controller: swagger_server.controllers.distance_controller
  /distance/registers:
    get:
      tags:
      - Distance
      summary: Return the distance between two given registers
      operationId: distance_registers_get
      parameters:
      - name: start_id_address
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: 655de875051df4458d1d32be
      - name: end_id_address
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: 6563ab4b514febb49306a795
      responses:
        "200":
          description: A number that represent the distance in meters
          content:
            application/json:
              schema:
                type: number
                example: 5725.929424237887
                x-content-type: application/json
        "400":
          description: Error message
          content:
            application/json:
              schema:
                type: string
                example: "An error has occurred: Address not found"
                x-content-type: application/json
      x-openapi-router-controller: swagger_server.controllers.distance_controller
components:
  schemas:
    Address:
      required:
      - city
      - country
      - district
      - state
      - street
      type: object
      properties:
        number:
          type: string
          example: "520"
        street:
          type: string
          example: AV. Pasteur
        district:
          type: string
          example: Urca
        city:
          type: string
          example: Rio de janeiro
        state:
          type: string
          example: RJ
        country:
          type: string
          example: Brazil

