# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Address(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, number: str=None, complement: str=None, street: str=None, district: str=None, city: str=None, state: str=None, country: str=None, cep: str=None):  # noqa: E501
        """Address - a model defined in Swagger

        :param number: The number of this Address.  # noqa: E501
        :type number: str
        :param complement: The complement of this Address.  # noqa: E501
        :type complement: str
        :param street: The street of this Address.  # noqa: E501
        :type street: str
        :param district: The district of this Address.  # noqa: E501
        :type district: str
        :param city: The city of this Address.  # noqa: E501
        :type city: str
        :param state: The state of this Address.  # noqa: E501
        :type state: str
        :param country: The country of this Address.  # noqa: E501
        :type country: str
        :param cep: The cep of this Address.  # noqa: E501
        :type cep: str
        """
        self.swagger_types = {
            'number': str,
            'complement': str,
            'street': str,
            'district': str,
            'city': str,
            'state': str,
            'country': str,
            'cep': str
        }

        self.attribute_map = {
            'number': 'number',
            'complement': 'complement',
            'street': 'street',
            'district': 'district',
            'city': 'city',
            'state': 'state',
            'country': 'country',
            'cep': 'cep'
        }
        self._number = number
        self._complement = complement
        self._street = street
        self._district = district
        self._city = city
        self._state = state
        self._country = country
        self._cep = cep

    @classmethod
    def from_dict(cls, dikt) -> 'Address':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Address of this Address.  # noqa: E501
        :rtype: Address
        """
        return util.deserialize_model(dikt, cls)

    @property
    def number(self) -> str:
        """Gets the number of this Address.


        :return: The number of this Address.
        :rtype: str
        """
        return self._number

    @number.setter
    def number(self, number: str):
        """Sets the number of this Address.


        :param number: The number of this Address.
        :type number: str
        """

        self._number = number

    @property
    def complement(self) -> str:
        """Gets the complement of this Address.


        :return: The complement of this Address.
        :rtype: str
        """
        return self._complement

    @complement.setter
    def complement(self, complement: str):
        """Sets the complement of this Address.


        :param complement: The complement of this Address.
        :type complement: str
        """

        self._complement = complement

    @property
    def street(self) -> str:
        """Gets the street of this Address.


        :return: The street of this Address.
        :rtype: str
        """
        return self._street

    @street.setter
    def street(self, street: str):
        """Sets the street of this Address.


        :param street: The street of this Address.
        :type street: str
        """
        if street is None:
            raise ValueError("Invalid value for `street`, must not be `None`")  # noqa: E501

        self._street = street

    @property
    def district(self) -> str:
        """Gets the district of this Address.


        :return: The district of this Address.
        :rtype: str
        """
        return self._district

    @district.setter
    def district(self, district: str):
        """Sets the district of this Address.


        :param district: The district of this Address.
        :type district: str
        """
        if district is None:
            raise ValueError("Invalid value for `district`, must not be `None`")  # noqa: E501

        self._district = district

    @property
    def city(self) -> str:
        """Gets the city of this Address.


        :return: The city of this Address.
        :rtype: str
        """
        return self._city

    @city.setter
    def city(self, city: str):
        """Sets the city of this Address.


        :param city: The city of this Address.
        :type city: str
        """
        if city is None:
            raise ValueError("Invalid value for `city`, must not be `None`")  # noqa: E501

        self._city = city

    @property
    def state(self) -> str:
        """Gets the state of this Address.


        :return: The state of this Address.
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state: str):
        """Sets the state of this Address.


        :param state: The state of this Address.
        :type state: str
        """
        if state is None:
            raise ValueError("Invalid value for `state`, must not be `None`")  # noqa: E501

        self._state = state

    @property
    def country(self) -> str:
        """Gets the country of this Address.


        :return: The country of this Address.
        :rtype: str
        """
        return self._country

    @country.setter
    def country(self, country: str):
        """Sets the country of this Address.


        :param country: The country of this Address.
        :type country: str
        """
        if country is None:
            raise ValueError("Invalid value for `country`, must not be `None`")  # noqa: E501

        self._country = country

    @property
    def cep(self) -> str:
        """Gets the cep of this Address.


        :return: The cep of this Address.
        :rtype: str
        """
        return self._cep

    @cep.setter
    def cep(self, cep: str):
        """Sets the cep of this Address.


        :param cep: The cep of this Address.
        :type cep: str
        """

        self._cep = cep
